name: Continuous integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint
        run: make lint

      - name: Build
        run: make build -j3

      - name: Test
        run: make test